### ISSUE TITLE
Support a Structured Output Format

### ISSUE THREAD

**Issue by prikhi** [zwilias/elm-xref#4]
For example, when passing a `--format=json` flag, have the entire stdout output be a JSON object.

My desire is to be able to call `elm-xref` from a Haskell build script, parse the output, and prettily print the warnings of multiple tools(this, `elm-analyse`, `elm-format --validate`, etc.).

I can currently parse the output format, but it'd be nice if I didn't have to tweak if the end-user formatting ever changes.

**Comment by zwilias** [comment]
Agreed!

**Comment by zwilias** [comment]
Released in 0.3.3!

For unused symbols, the format is a JSON array where each element has the file, row, column, module and symbol name. If there are no unused symbols, the process exits with 0, otherwise it's a 1.

For usages, it's an array where each element has the module, function and line-numbers where the symbol you're looking for is used. This always exits with a 0 exit code.
